postgres:
	docker run --name postgres14 -p 5435:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d e09e90144645

createdb: 
	docker exec -it postgres14 createdb --username=root --owner=root simplebank

dropdb: 
	docker exec -it dropdb simplebank

migrateup:
	migrate -path db/migration -database="postgresql://root:secret@localhost:5435/simplebank?sslmode=disable" -verbose up

migratedown:
	migrate -path db/migration -database="postgresql://root:secret@localhost:5435/simplebank?sslmode=disable" -verbose down

sqlc:
	docker run --rm -v "%cd%:/src" -w /src kjconroy/sqlc generate


.PHONY: postgres createdb dropdb migrateup migratedown sqlc